### ISSUE TITLE
Promise function is execute before queue

### ISSUE THREAD

**Issue by dArignac** [gustavolaux/promise-queue-manager#16]
Hi,

just stumbled over your library and checked the tests to learn how it works. I have a question regarding usage of `promises` within the config.

In the second (and following) test you declare:

```
const config = {
  promises: [1, 2, 3, 4, 5].map((ms) => getMockPromise(ms)),
};
```

having `getMockPromise` as `const getMockPromise = (ms = 0, shouldResolve = true) => { ... };`

Won't this declaration directly execute the `getMockPromise` function even before your queue is started?
Shouldn't `getMockPromise` have a signature to just return the promise reference but not yet execute it?

Thanks for clarification!

**Comment by gustavolaux** [comment]
Hi, Alexander!

First of all, thanks for your feedback. Exactly, it will execute the `setTimeout` right away. It happens because `Promise` constructor is synchronously executed and there is no way to do it differently

https://262.ecma-international.org/6.0/#sec-promise-executor
```
Returning from the executor function does not mean that the deferred action has been completed but only that the request to eventually perform the deferred action has been accepted
```

The tests are there to ensure the no unwanted errors are throwed. Maybe they need to be rethought....

**Comment by dArignac** [comment]
Hi Gustavo,

thanks for your answer and of course for providing the lib!

When using `config.promise` and `config.items` everything works fine, as the method is executed when the chain is processed. The promises in the list `promises` instead get called directly, so the execution is already done when the chain handling is done. The concurrency property also has no effect in this setup.

Would it be possible to adjust or extend the lib, so that instead of giving in a list of promises `Promise<T>[]` we give in a list with wrapped promises, which are then executed in the chain `Array<() => Promise<T>>`. With this approach the promises would be executed the same way as when giving in `promise` and `items`.

I'm not sure if that is a wanted behaviour of yours, so I'm asking - thanks!

**Comment by gustavolaux** [comment]
hey @dArignac, sorry about the (huge hehehe) delay. can you check the PR #19 if this problem is solved? thanks!

**Comment by dArignac** [comment]
Hey @gustavolaux, actually don't remember where I had the issue 🤷🏻 
But thanks a lot for fixing it!
